// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV-Spr1GzhvDGVAaUxWhk-A3ieiPE8vR8',
    appId: '1:573656772366:web:bb3c38c3bba66ceec8f15f',
    messagingSenderId: '573656772366',
    projectId: 'joonggaego',
    authDomain: 'joonggaego.firebaseapp.com',
    storageBucket: 'joonggaego.firebasestorage.app',
    measurementId: 'G-B2FE4ZW9LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAthWPe00nybgBdsG6atzdQLX26oucQl7g',
    appId: '1:573656772366:android:593e63ecfc39e657c8f15f',
    messagingSenderId: '573656772366',
    projectId: 'joonggaego',
    storageBucket: 'joonggaego.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE4IFVdITVsjrDpk75gIFKey3Jeth2WiE',
    appId: '1:573656772366:ios:c012070851860fbac8f15f',
    messagingSenderId: '573656772366',
    projectId: 'joonggaego',
    storageBucket: 'joonggaego.firebasestorage.app',
    iosBundleId: 'com.jylee.joonggaego',
  );
}
